version: '3.7'
services:
  node:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-projet
    container_name: vue-docker
    restart: unless-stopped
    command: npm run serve
    ports:
    - '8080:8080'
    volumes:
      - ./:/app/
      - /app/node_modules
